# Generated by Django 4.1.2 on 2023-01-19 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_response_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='grade_acheived',
            new_name='grade_achieved',
        ),
        migrations.AddField(
            model_name='response',
            name='quiz',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
            preserve_default=False,
        ),
    ]
