# Generated by Django 4.1.6 on 2023-02-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_alter_instructor_instructor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
