# Generated by Django 4.1.6 on 2023-03-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_alter_instructor_instructor_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_solution',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
